dist: xenial
language: cpp
compiler: gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libboost-test-dev
    - g++-7
    - doxygen
    - graphviz
env:
  - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
before_install:
    - eval "${MATRIX_EVAL}"
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
- doxygen .doxygen.conf
- printenv
deploy:
  - provider: script
    edge: true
    script:
    - curl -f -T print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -ucrogst:$bintray_api_key "https://api.bintray.com/content/crogst/Repository/otus-cpp/$TRAVIS_BUILD_NUMBER/print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"
  - provider: pages
    skip_cleanup: true
    keep_history: true
    github_token: $GITHUB_TOKEN
    local_dir: html
    on:
      branch: master
